# Generated by Django 5.0.6 on 2024-05-15 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('amount', models.FloatField(default=0.0)),
                ('currency', models.CharField(max_length=3)),
                ('paid_on', models.DateTimeField()),
                ('share_bitween', models.JSONField()),
                ('share_type', models.CharField(choices=[('EQUAL', 'Equal'), ('EXACT', 'Exact'), ('PERCENT', 'Percent')], default='EQUAL', max_length=8)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SETTLED_UP', 'Settled Up')], default='EQUAL', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('user_id', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('mobile_no', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_id', models.UUIDField()),
                ('amount', models.FloatField(default=0.0)),
                ('currency', models.CharField(max_length=3)),
                ('paid_on', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('PAID', 'Paid')], default='PENDING', max_length=12)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='txn_expense', to='splitwise_app.expense')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='txn_from_user', to='splitwise_app.user')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='txn_to_user', to='splitwise_app.user')),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_added_by', to='splitwise_app.user'),
        ),
        migrations.AddField(
            model_name='expense',
            name='paid_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_paid_by', to='splitwise_app.user'),
        ),
        migrations.CreateModel(
            name='AccountSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simplyfy', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_acc_setting', to='splitwise_app.user')),
            ],
        ),
    ]
